### ISSUE TITLE
ios 9 https ATS

### ISSUE THREAD

**Issue by dermaaarkus** [nicklockwood/iVersion#84]
Hi,

i'm currently prepare my app for iOS 9 and App Transport Security (ATS). In my app logs occurs:

> iVersion is checking http://itunes.apple.com/DE/lookup?id=******** for a new app version...

Is it possible to change http to https to fully support ATS? Or are apple domains somehow explicit trusted?

Thanks in advance!

Markus

**Comment by nicklockwood** [comment]
Fixed in 1.11.5
